[workspace]
members = ["packages/*"]

[workspace.package]
authors    = ["larry <gm@larry.engineer>"]
edition    = "2021"
homepage   = "https://larry.engineer"
repository = "https://github.com/larry0x/cw-plus-plus"
license    = "Apache-2.0"
version    = "3.0.1"
keywords   = ["cosmos", "cosmwasm"]

[workspace.dependencies]
cw-address-like = { path = "packages/address-like" }
cw-ownable-derive = { version = "3.0.1", path = "./packages/ownable/derive" }
proc-macro2       = "1"
quote             = "1"
serde             = { version = "1", default-features = false }
syn               = "1"
thiserror         = "1"

cosmwasm-schema = { path = "../cosmwasm/packages/schema" }
cosmwasm-std = { path = "../cosmwasm/packages/std" }
cw-storage-plus = { path = "../cw-storage-plus" }
cw-utils = { path = "../cw-minus/packages/cw-utils" }

[patch.'https://github.com/permissionlessweb/cw-plus-plus']
cw-address-like = { path = "packages/address-like" }
cw-ownable = { path = "packages/ownable" }
cw-paginate = { path = "packages/paginate" }
